export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';
export const PROJECT_CREATE_RESET = 'PROJECT_CREATE_RESET';

export const PROJECT_SET_CURRENT = 'PROJECT_SET_CURRENT';
export const PROJECT_SET_CURRENT_RESET = 'PROJECT_SET_CURRENT_RESET';

export const PROJECT_GET_DATA_REQUEST = 'PROJECT_GET_DATA_REQUEST';
export const PROJECT_GET_DATA_SUCCESS = 'PROJECT_GET_DATA_SUCCESS';
export const PROJECT_GET_DATA_FAIL = 'PROJECT_GET_DATA_FAIL';
export const PROJECT_GET_DATA_RESET = 'PROJECT_GET_DATA_RESET';
export const PROJECT_GET_DATA_ADD_TASK = 'PROJECT_GET_DATA_ADD_TASK';
