export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';
export const PROJECT_CREATE_RESET = 'PROJECT_CREATE_RESET';

export const PROJECT_SET_CURRENT = 'PROJECT_SET_CURRENT';
export const PROJECT_SET_CURRENT_RESET = 'PROJECT_SET_CURRENT_RESET';

export const PROJECT_DATA_REQUEST = 'PROJECT_DATA_REQUEST';
export const PROJECT_DATA_SUCCESS = 'PROJECT_DATA_SUCCESS';
export const PROJECT_DATA_FAIL = 'PROJECT_DATA_FAIL';
export const PROJECT_DATA_RESET = 'PROJECT_DATA_RESET';
export const PROJECT_DATA_ADD_TASK = 'PROJECT_DATA_ADD_TASK';
export const PROJECT_DATA_MOVE_TASK = 'PROJECT_DATA_MOVE_TASK';
export const PROJECT_DATA_UPDATE_LISTS = 'PROJECT_DATA_UPDATE_LISTS';

export const PROJECT_TASK_MOVE = 'PROJECT_TASK_MOVE';
export const PROJECT_TASK_MOVE_RESET = 'PROJECT_TASK_MOVE_RESET';
