export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_DATA_UPDATE = 'USER_DATA_UPDATE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_NOTIFICATIONS_UPDATE = 'USER_NOTIFICATIONS_UPDATE';
export const USER_REMOVED = 'USER_REMOVED';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_EMAIL_CONFIRM_REQUEST = 'USER_EMAIL_CONFIRM_REQUEST';
export const USER_EMAIL_CONFIRM_SUCCESS = 'USER_EMAIL_CONFIRM_SUCCESS';
export const USER_EMAIL_CONFIRM_FAIL = 'USER_EMAIL_CONFIRM_FAIL';

export const USER_EMAIL_RESEND_REQUEST = 'USER_EMAIL_RESEND_REQUEST';
export const USER_EMAIL_RESEND_SUCCESS = 'USER_EMAIL_RESEND_SUCCESS';
export const USER_EMAIL_RESEND_FAIL = 'USER_EMAIL_RESEND_FAIL';

export const USER_PICTURE_UPDATE_REQUEST = 'USER_PICTURE_UPDATE_REQUEST';
export const USER_PICTURE_UPDATE_SUCCESS = 'USER_PICTURE_UPDATE_SUCCESS';
export const USER_PICTURE_UPDATE_FAIL = 'USER_PICTURE_UPDATE_FAIL';

export const USER_PROJECT_BG_UPDATE_REQUEST = 'USER_PROJECT_BG_UPDATE_REQUEST';
export const USER_PROJECT_BG_UPDATE_SUCCESS = 'USER_PROJECT_BG_UPDATE_SUCCESS';
export const USER_PROJECT_BG_UPDATE_FAIL = 'USER_PROJECT_BG_UPDATE_FAIL';
